# Generated by Django 5.0.4 on 2024-04-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subreq',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='subreq',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='subreq',
            name='created_at',
        ),
    ]
