# Generated by Django 5.0.4 on 2024-04-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_fname_subreq_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subreq',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='subreq',
            old_name='last_name',
            new_name='lname',
        ),
    ]
