# Generated by Django 5.0.4 on 2024-04-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_first_name_subreq_fname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subreq',
            new_name='subrequest',
        ),
    ]
